name: CI/CD - Build, Test, Push Docker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ci-cd-docker-github-actions-starter/requirements-dev.txt

      - name: Lint with ruff
        run: ruff check .

      - name: Run tests with coverage
        run: |
          cd ci-cd-docker-github-actions-starter
          PYTHONPATH=. pytest -q --cov=app --cov-report=term-missing --cov-fail-under=80

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./ci-cd-docker-github-actions-starter
          file: ./ci-cd-docker-github-actions-starter/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/flask-ci-cd:${{ github.sha }},${{ secrets.DOCKER_USERNAME }}/flask-ci-cd:staging

      - name: Scan image with Trivy (security)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/flask-ci-cd:${{ github.sha }}
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
   